import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import * as risk from "../js/risk.js";
import * as strategy from "../js/strategy.js";
import * as profile from "../js/profile.js";
import * as reasoner from "../js/reasoner.js";
import {
  SCENARIOS,
  runCounterfactual,
  validateScenarioProposal,
  isAllowedChangePath,
} from "../js/counterfactual.js";

const load = async (path) =>
  JSON.parse(await readFile(new URL(`../${path}`, import.meta.url), "utf8"));

const [MARKET, GRAPH, RULES, REGISTRY, SCHEMA] = await Promise.all([
  load("test/fixtures/golden-market.json"),
  load("data/knowledge-graph.json"),
  load("data/eligibility-rules.json"),
  load("data/source-registry.json"),
  load("data/ontology-schema.json"),
]);

const GOLDEN_TRANSACTIONS = [
  {
    transaction_id: "txn-usd-in-3m",
    country: "US",
    currency: "USD",
    tradeType: "export",
    direction: "in",
    amount: 300_000,
    months: 3,
  },
  {
    transaction_id: "txn-usd-out-2m",
    country: "US",
    currency: "USD",
    tradeType: "import",
    direction: "out",
    amount: 100_000,
    months: 2,
  },
  {
    transaction_id: "txn-eur-out-4m",
    country: "DE",
    currency: "EUR",
    tradeType: "import",
    direction: "out",
    amount: 80_000,
    months: 4,
  },
];

const GOLDEN_INPUT = {
  transactions: GOLDEN_TRANSACTIONS,
  rates: MARKET.rates,
  annualVol: MARKET.annual_vol,
  liquidity: { openingBalanceKrw: 50_000_000, creditLineKrw: 20_000_000 },
  company: {
    companyType: "corporation",
    isSme: true,
    riskAppetite: "low",
    existingHedges: [],
    requestedPurposes: ["fx_hedge", "working_capital", "guarantee_insurance"],
    creditGradeMeetsThreshold: true,
    priorYearExportUsd: 1_000_000,
    reviewChannelConfirmed: true,
    internetBankingEnrolled: true,
  },
  today: MARKET.as_of,
};

const deps = () => ({
  engines: { risk, strategy, profile, reasoner },
  graph: GRAPH,
  rules: RULES,
  sources: REGISTRY.sources,
  schema: SCHEMA,
});

// Independent formula, not generated by runCounterfactual:
// USD out 100k@2m + delayed USD in 300k@4m + EUR out 80k@4m,
// each |net| × rate × annual σ × sqrt(months/12) × 1.645.
const EXPECTED_DELAY_CFAR = 49_297_391;
const EXPECTED_ADVERSE_FX_PNL = -19_864_200;

test("payment delay targets a transaction by id and re-runs the engines (exact golden)", () => {
  const result = runCounterfactual(
    "payment_delay_1m",
    GOLDEN_INPUT,
    deps(),
    { targetTransactionId: "txn-usd-in-3m" },
  );

  assert.equal(result.scenario.targetTransactionId, "txn-usd-in-3m");
  assert.deepEqual(result.changedInputs, [{
    path: "transactions.id~00740078006e002d007500730064002d0069006e002d0033006d.months",
    before: 3,
    after: 4,
  }]);
  assert.equal(Math.round(result.after.cfar.total), EXPECTED_DELAY_CFAR);
  assert.notDeepEqual(result.before.liquidity, result.after.liquidity);
});

test("default delay target is the largest receivable and its deterministic tie-break is explicit", () => {
  const result = runCounterfactual("payment_delay_1m", GOLDEN_INPUT, deps());
  assert.equal(result.scenario.targetTransactionId, "txn-usd-in-3m");
  assert.match(result.scenario.targetScopeLabel, /가장 큰 수취/);

  const tieInput = structuredClone(GOLDEN_INPUT);
  tieInput.transactions.push({
    transaction_id: "txn-a-tie",
    country: "US",
    currency: "USD",
    tradeType: "export",
    direction: "in",
    amount: 300_000,
    months: 2,
  });
  const tie = runCounterfactual("payment_delay_1m", tieInput, deps());
  assert.equal(tie.scenario.targetTransactionId, "txn-a-tie", "shorter maturity wins the tie");
});

test("revenue drop states its scope and recomputes without a monotonicity claim", () => {
  const result = runCounterfactual(
    "revenue_drop_30",
    GOLDEN_INPUT,
    deps(),
    { scope: "all_receivables" },
  );
  assert.match(result.scenario.targetScopeLabel, /모든 수취/);
  assert.equal(result.changedInputs.length, 1);
  for (const change of result.changedInputs)
    assert.equal(Math.round(change.after), Math.round(change.before * 0.7));
  assert.notDeepEqual(result.before.cfar, result.after.cfar);
  assert.ok(result.explanationFacts.every((fact) => !/위험.*개선|안전해졌/.test(fact.text)));
});

test("revenue drop prefers explicitly selected export transactions and identifies them by id", () => {
  const result = runCounterfactual(
    "revenue_drop_30",
    GOLDEN_INPUT,
    deps(),
    { targetTransactionIds: ["txn-usd-in-3m"] },
  );
  assert.match(result.scenario.targetScopeLabel, /선택된 수출/);
  assert.deepEqual(result.changedInputs.map((change) => change.path), [
    "transactions.id~00740078006e002d007500730064002d0069006e002d0033006d.amount",
  ]);
});

test("without selected exports, revenue drop defaults to every receivable as specified", () => {
  const input = structuredClone(GOLDEN_INPUT);
  input.transactions.push({
    transaction_id: "txn-import-receivable",
    country: "US",
    currency: "USD",
    tradeType: "import",
    direction: "in",
    amount: 10_000,
    months: 1,
  });
  const result = runCounterfactual("revenue_drop_30", input, deps());
  assert.match(result.scenario.targetScopeLabel, /모든 수취/);
  assert.deepEqual(result.changedInputs.map((change) => change.path), [
    "transactions.id~00740078006e002d007500730064002d0069006e002d0033006d.amount",
    "transactions.id~00740078006e002d0069006d0070006f00720074002d00720065006300650069007600610062006c0065.amount",
  ]);
});

test("over-hedge is flagged only on same currency+maturity; unmapped hedges stay pending", () => {
  const sameBucket = structuredClone(GOLDEN_INPUT);
  sameBucket.company.existingHedges = [{
    currency: "USD",
    amount: 250_000,
    maturityMonths: 3,
    instrumentType: "forward",
  }];
  const flagged = runCounterfactual("revenue_drop_30", sameBucket, deps());
  assert.ok(flagged.explanationFacts.some((fact) =>
    /과헤지/.test(fact.text) && fact.mapping === "same_bucket"));

  const unmapped = structuredClone(GOLDEN_INPUT);
  unmapped.company.existingHedges = [{
    currency: "JPY",
    amount: 10_000_000,
    maturityMonths: 1,
    instrumentType: "forward",
  }];
  const pending = runCounterfactual("revenue_drop_30", unmapped, deps());
  assert.ok(pending.explanationFacts.some((fact) =>
    fact.mapping === "unmapped" && /판정 보류|매핑할 수 없/.test(fact.text)));
  assert.ok(!pending.explanationFacts.some((fact) =>
    fact.mapping === "same_bucket" && /과헤지/.test(fact.text)));
});

test("adverse FX separates scenarioPnL from recomputed CFaR and applies currency-specific direction", () => {
  const result = runCounterfactual("adverse_fx_5", GOLDEN_INPUT, deps());
  assert.equal(Math.round(result.after.scenarioPnL), EXPECTED_ADVERSE_FX_PNL);
  assert.equal(Math.round(result.deltas.scenarioPnlKrw), EXPECTED_ADVERSE_FX_PNL);
  assert.ok(Number.isFinite(result.deltas.cfarTotalKrw));

  const usd = result.changedInputs.find((change) => change.path === "rates.USD");
  const eur = result.changedInputs.find((change) => change.path === "rates.EUR");
  assert.ok(usd.after < usd.before, "USD net receivable must receive a downward adverse shock");
  assert.ok(eur.after > eur.before, "EUR net payable must receive an upward adverse shock");
  assert.ok(result.explanationFacts.every((fact) => !/위험.*개선|안전해졌/.test(fact.text)));
});

test("only scenario-approved fields change and the original input is never mutated", () => {
  for (const scenario of SCENARIOS.filter((item) => item.implemented)) {
    const original = structuredClone(GOLDEN_INPUT);
    const result = runCounterfactual(scenario.id, GOLDEN_INPUT, deps());
    assert.deepEqual(GOLDEN_INPUT, original);
    for (const change of result.changedInputs)
      assert.equal(isAllowedChangePath(scenario.id, change.path), true, change.path);
  }
});

test("the two P1 scenarios exist only as disabled metadata until T8.5c", () => {
  assert.equal(SCENARIOS.length, 5);
  const disabled = SCENARIOS.filter((scenario) => !scenario.implemented);
  assert.deepEqual(disabled.map((scenario) => scenario.id), [
    "early_termination",
    "eligibility_miss",
  ]);
  for (const scenario of disabled) {
    assert.equal(scenario.priority, "P1");
    assert.equal(validateScenarioProposal({ id: scenario.id, changes: [] }).ok, false);
    assert.throws(
      () => runCounterfactual(scenario.id, GOLDEN_INPUT, deps()),
      /준비 중|구현되지/,
    );
  }
});

test("counterfactual orchestration reuses frozen engines instead of duplicating financial formulas", async () => {
  const source = await readFile(new URL("../js/counterfactual.js", import.meta.url), "utf8");
  for (const call of [
    "computeCFaRBuckets",
    "portfolioCFaR",
    "bucketNotionalKrw",
    "liquidityTimeline",
    "compareStrategies",
    "buildProfile",
    "recommend",
  ]) assert.match(source, new RegExp(call));
  assert.doesNotMatch(source, /Math\.sqrt|1\.645/, "CFaR formula must remain in risk.js only");
});

test("recommendations are re-derived, carry reasoning paths and never gain score/rank", () => {
  const result = runCounterfactual("revenue_drop_30", GOLDEN_INPUT, deps());
  for (const key of ["added", "removed", "movedToPending"])
    assert.ok(Array.isArray(result.affectedRecommendations[key]));
  assert.deepEqual(result.after.recommendations.candidates.map((candidate) => candidate.product_id), [
    "fx_insurance",
    "trade_loan",
    "ecg_pre",
  ]);
  for (const candidate of result.after.recommendations.candidates) {
    assert.ok(candidate.reasoningPath.length > 0);
    assert.ok(!("score" in candidate) && !("rank" in candidate));
  }
  assert.doesNotMatch(JSON.stringify(result.after.recommendations), /"(score|rank)"\s*:/);
});

test("a candidate moved to pending is reported once, never also as removed", () => {
  let recommendationCall = 0;
  const product = { purpose: "fx_hedge", product_id: "demo_product" };
  const transitionDeps = deps();
  transitionDeps.engines.reasoner = {
    recommend() {
      recommendationCall += 1;
      return recommendationCall === 1
        ? { candidates: [product], pending: [], excluded: [], unavailable: [] }
        : { candidates: [], pending: [product], excluded: [], unavailable: [] };
    },
  };

  const result = runCounterfactual("payment_delay_1m", GOLDEN_INPUT, transitionDeps);
  assert.deepEqual(result.affectedRecommendations.removed, []);
  assert.deepEqual(result.affectedRecommendations.movedToPending, [{
    product_id: "demo_product",
    purpose: "fx_hedge",
    from: "candidate",
    to: "needs_information",
  }]);
});

test("LLM-proposed changes run only when they match the approved scenario schema", () => {
  assert.equal(validateScenarioProposal({
    id: "made_up",
    changes: [{ path: "cfar.total", after: 0 }],
  }).ok, false);
  assert.equal(validateScenarioProposal({
    id: "payment_delay_1m",
    changes: [{ path: "transactions.txn-usd-in-3m.months", after: 4 }],
  }).ok, false);
  assert.equal(validateScenarioProposal({
    id: "payment_delay_1m",
    changes: [{
      path: "transactions.id~00740078006e002d007500730064002d0069006e002d0033006d.months",
      after: 4,
    }],
  }).ok, true);
  assert.equal(validateScenarioProposal({
    id: "payment_delay_1m",
    changes: [{ path: "cfar.total", after: 0 }],
  }).ok, false);
});

test("LLM proposal paths reject prototype traversal segments, including encoded forms", () => {
  for (const path of [
    "rates.__proto__",
    "rates.constructor",
    "rates.prototype",
    "rates.%5F%5Fproto%5F%5F",
    "transactions.constructor.months",
    "transactions.%255F%255Fproto%255F%255F.months",
  ]) {
    const id = path.startsWith("rates.") ? "adverse_fx_5" : "payment_delay_1m";
    assert.equal(validateScenarioProposal({
      id,
      changes: [{ path, after: 1 }],
    }).ok, false, path);
  }

  assert.equal(validateScenarioProposal({
    id: "adverse_fx_5",
    changes: [{ path: "rates.USD", after: 950 }],
  }).ok, true);
});

test("malformed or ambiguous transaction targeting fails closed", () => {
  assert.throws(
    () => runCounterfactual("payment_delay_1m", GOLDEN_INPUT, deps(), {
      targetTransactionId: "missing",
    }),
    /거래 ID|target/i,
  );

  const duplicate = structuredClone(GOLDEN_INPUT);
  duplicate.transactions[1].transaction_id = duplicate.transactions[0].transaction_id;
  assert.throws(
    () => runCounterfactual("payment_delay_1m", duplicate, deps()),
    /중복/,
  );
});

test("user-provided transaction ids are preserved while change paths remain unambiguous", () => {
  const input = structuredClone(GOLDEN_INPUT);
  input.transactions[0].transaction_id = "client.txn/1";
  const result = runCounterfactual(
    "payment_delay_1m",
    input,
    deps(),
    { targetTransactionId: "client.txn/1" },
  );
  assert.equal(result.scenario.targetTransactionId, "client.txn/1");
  assert.equal(
    result.changedInputs[0].path,
    "transactions.id~0063006c00690065006e0074002e00740078006e002f0031.months",
  );
  assert.equal(isAllowedChangePath("payment_delay_1m", result.changedInputs[0].path), true);
});

test("reserved transaction ids remain addressable through a safe encoded path segment", () => {
  const input = structuredClone(GOLDEN_INPUT);
  input.transactions[0].transaction_id = "__proto__";
  const result = runCounterfactual(
    "payment_delay_1m",
    input,
    deps(),
    { targetTransactionId: "__proto__" },
  );
  assert.equal(result.scenario.targetTransactionId, "__proto__");
  assert.equal(
    result.changedInputs[0].path,
    "transactions.id~005f005f00700072006f0074006f005f005f.months",
  );
  assert.equal(isAllowedChangePath("payment_delay_1m", result.changedInputs[0].path), true);
});

test("percent-bearing transaction ids generate paths accepted by the same allowlist", () => {
  for (const transactionId of ["%", "%E0%A4%A", "%5F%5Fproto%5F%5F"]) {
    const input = structuredClone(GOLDEN_INPUT);
    input.transactions[0].transaction_id = transactionId;
    const result = runCounterfactual(
      "payment_delay_1m",
      input,
      deps(),
      { targetTransactionId: transactionId },
    );
    assert.equal(
      isAllowedChangePath("payment_delay_1m", result.changedInputs[0].path),
      true,
      transactionId,
    );
  }
});

test("distinct transaction ids always produce distinct change-path segments", () => {
  const transactionIds = ["__proto__", "id:__proto__", "constructor", "id:constructor"];
  const paths = transactionIds.map((transactionId) => {
    const input = structuredClone(GOLDEN_INPUT);
    input.transactions[0].transaction_id = transactionId;
    return runCounterfactual(
      "payment_delay_1m",
      input,
      deps(),
      { targetTransactionId: transactionId },
    ).changedInputs[0].path;
  });

  assert.equal(new Set(paths).size, transactionIds.length);
});

test("same input produces a byte-identical counterfactual result", () => {
  const first = runCounterfactual("adverse_fx_5", GOLDEN_INPUT, deps());
  const second = runCounterfactual("adverse_fx_5", GOLDEN_INPUT, deps());
  assert.equal(JSON.stringify(first), JSON.stringify(second));
});
